version: '3.8'

services:
  calculator:
    image: calculator-microservice
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/usr/src/app/logs
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
